
title = "blog"
intro = "简单内容管理-blog"
mode = "dev"
addr = ":8085"
srv = "http://127.0.0.1:8085"

# token 相关
token_key = "token"
# 过期时间 h
token_exp = 24
# 单点登录
token_sso =false
# 保持在线
token_keep = false
# 加密私钥
token_secret ="secret"

# 系统
# 图片裁剪
image_cut = false
image_width = 800
image_height =600
# 分页
page_min = 5
page_max = 30

# 数据库
# https://github.com/go-sql-driver/mysql
# 数据库地址
db_host = "127.0.0.1"
# 数据库端口
db_port = 3306
# 数据库账号
db_user = "root"
# 数据库密码
db_passwd = "root"
# 数据库名称
db_name = "blog"
# 数据库参数
db_params = "charset=utf8&parseTime=true&loc=Local"

# orm
# https://gitea.com/xorm/xorm
# 推荐cpu核心数
orm_idle = 4
# 推荐cpu核心数*2
orm_open = 8
# 显示sql
orm_show = true 
# 同步表结构
orm_sync = false
# 是否使用orm缓存
orm_cache_use = false 
# orm缓存数量
orm_cache_size = 1000
# orm劫持日志输出
orm_hijack_log = true

# 作者
[author]
name = "zxysilent"
website = "https://github.com/zxysilent"

# 微信相关 
# 移动 网站 https://open.weixin.qq.com/cgi-bin/index
# 公众号 小程序 https://mp.weixin.qq.com/
[wechat]
# 需要适配多个,这里列举一个目标
# 请同时修改 conf.go
xxx_appid = "appid"
xxx_secret = "secret"
